config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :links, except: [:delete]
  post "/links/:id/edit", to: "links#update", as: "edit_link_submission"

  root "links#index"
  get "/logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
require 'uri'

class Link < ApplicationRecord
  belongs_to :user

  validates :url, presence: true
  validates :title, presence: true
  validates :read, absence: false
  validates :user_id, presence: true

  def validate_url(url = self.url)
    if url.split(" ").length > 1
      self.url = url.split(" ")[0]
      send_email(url) if url.split(" ").length == 3
    end
    uri = URI.parse(self.url)
    uri.kind_of?(URI::HTTP)
  rescue URI::InvalidURIError
    false
  end

  def send_email(user_input)
    ApplicationMailer.send_email(user_input.split(" ")[2], self).deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :links

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :user_logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_logged_in?
    session[:user_id]
  end

  def authorize
    unless user_logged_in?
      flash[:notice] = "You must be logged in to continue!"
      redirect_to new_session_path
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :authorize

  def index
    @links = current_user.links
  end

  def create
    link = Link.new(link_params)
    if link.validate_url(link.url) && link.save
      flash[:notice] = "Link was Added!"
    else
      flash[:alert] = "Link is invalid. Check URL, Title, and '\cc:'"
    end
    redirect_to root_path
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    link = Link.find(params[:id])
    if link.validate_url(link_params[:url]) && link_params[:title].length > 0
      link.update_attributes(link_params)
      flash[:notice] = "Link was updated!"
    else
      flash[:alert] = "Link is invalid. Check URL, Title, and '\cc:'"
    end
    redirect_to root_path
  end

  private

  def link_params
    params.require(:link).permit(:title, :url, :user_id, :read)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:alert] = "Login Error"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    validate_password_confirmation
  end

  private

  def determine_user_validation_error
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def validate_password_confirmation
    if params[:user][:password] != params[:user][:password_confirm]
      flash[:alert] = "Error: Password did not match"
      redirect_to new_user_path
    else
      validate_user_creation
    end
  end

  def validate_user_creation
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:alert] = "Error: Email is already in use"
      redirect_to new_user_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "URLockbox" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render partial: "shared/navbar" %>

    <% if flash[:alert] %>
      <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <% if flash[:notice] %>
      <div class="notice">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/links/edit.html.erb
<div class="callout large primary text-center">
  <h3>Edit Link Information</h3>
</div>

<div class="row">
  <div class="large-6 medium-6 large-centered medium-centered columns">
    <%= render partial: "shared/link_form" %>
  </div>
</div>

app/views/links/index.html.erb
 <div class="container" id="content">
  <div class="row">
    </br>
    <div class="large-4 medium-4 columns">
      <h3 class="text-center">New Link Entry:</h3>
      <%= render partial: "shared/link_form" %>
    </div>

    <div class="large-8 medium-8 columns">
      <h3 class="text-center">My Links:</h3>
      <hr>
      <div class="large-4 medium-4 columns text-center">
        </br>
        <a id="link_sort">Sort by Title</a>
        <a id="link_unsort" class="hidden">Unsort</a>
      </div>
      <div class="large-4 medium-4 columns text-center">
        <label>Search by Title:</label>
        <%= text_field :link, :search %>
      </div>
      <div class="large-4 medium-4 columns text-center">
        <a id="read_filter">Show Read</a><br />
        <a id="unread_filter">Show Unread</a><br />
        <a id="all_filter">Show All</a>
      </div>
      <table>
        <thead>
          <tr>
            <th class="text-center"></th>
            <th class="text-center">Title</th>
            <th class="text-center">URL</th>
            <th class="text-center">Status</th>
            <th class="text-center">Change Status</th>
          </tr>
        </thead>
        <tbody>
          <% @links.each do |link| %>
            <% if link.read %>
              <tr class="strikeout link_details text-center" data-title="<%= link.title %>">
                <%= render partial: "shared/link_row_display", locals: { link: link, status: false } %>
              </tr>
            <% else %>
              <tr class="link_details text-center" data-title="<%= link.title %>">
                <%= render partial: "shared/link_row_display", locals: { link: link, status: true } %>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/shared/_link_form.html.erb
<%= form_for :link do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :url, "URL" %>
  <%= f.text_field :url %>

  <%= f.hidden_field :user_id, value: session[:user_id] %>

  <%= f.submit "Save", class: "button large expanded" %>
<% end %>

app/views/shared/_link_row_display.html.erb
<td><%= link_to "Edit", edit_link_path(link), id: "edit-link-#{link.id}" %></td>
<td><%= link.title %></td>
<td><%= link_to "#{link.url}", link.url %></td>
<td><%= link.read ? "Read" : "Unread" %></td>
<td><%= link_to "Change Status", link_path(id: link.id, link: { url: link.url, title: link.title, read: status }), method: :patch, class: "read_status_change", id: "#{link.id}", remote: true %></td>

app/views/shared/_navbar.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="menu">
      <li class="menu-text">
        URL LockBox
      </li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <% if user_logged_in? %>
        <li>
          <%= "Logged in as " + current_user.email %>
        </li>
        <li>
          <%= link_to "Logout", "/logout" %>
        </li>
        <% else %>
        <li>
          <%= link_to "Log In", controller: "sessions", action: "new" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/new.html.erb
<div class="callout large primary text-center">
  <h3>New User Sign Up</h3>
</div>

<div class="row" id="content">
  <div class="large-6 medium-6 large-centered medium-centered columns">
    <h5>Sign Up:</h5>
    <%= form_for :user, url: users_path, html: {method: :post} do |f| %>
      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirm, "Password Confirmation" %>
      <%= f.password_field :password_confirm %>

      <%= f.submit "Sign Up", class: "button large expanded" %>
    <% end %>
  </div>
</div>